/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// INCLUDES
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>

#include "digital_io.h"
#include "serial.h"
#include "timer.h"
#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	enable_clocks();
	initialise_board();
	enable_timer3_interrupt();
	SerialInitialise(BAUD_115200, &USART1_PORT);


    /* Loop forever */
	for(;;);
}
